image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    - db: MySQL

    - db: PostgreSQL

for:
  -
    matrix:
      only:
        - db: MySQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v4.20.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /home/appveyor/projects/diplom2023/docker-compose.yml up
      - sleep 20
      - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" -jar artifacts/aqa-shop.jar &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew clean test "-Ddb.url=jdbc:mysql://localhost:3306/app"
      - sudo docker-compose down

  -
    matrix:
      only:
        - db: PostgreSQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v4.20.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /home/appveyor/projects/diplom2023/docker-compose.yml up
      - sleep 20
      - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" -jar artifacts/aqa-shop.jar &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew clean test "-Ddb.url=jdbc:postgresql://localhost:5432/app"
      - sudo docker-compose down
